---

- name: setup group
  group:
    name: "{{pritunl_group}}"
    system: false

- name: setup user
  user:
    name: "{{pritunl_user}}"
    system: false
    group: "{{pritunl_group}}"

- name: setup group
  group:
    name: "{{mongo_group}}"
    system: false

- name: setup user
  user:
    name: "{{mongo_user}}"
    system: false
    group: "{{mongo_group}}"
